# Generated by Django 2.0.12 on 2020-03-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Property_status', models.CharField(choices=[('Property for sale', 'Property for sale'), ('Property for rent', 'Property for rent')], max_length=30, verbose_name='Property type')),
                ('price', models.IntegerField(blank=True, help_text='Set Price', null=True, verbose_name='Price')),
            ],
        ),
    ]
