# Generated by Django 2.0.12 on 2020-03-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0003_announcement_propertytype_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='Bathrooms',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bathrooms'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='Bedrooms',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bedrooms'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='Featuers',
            field=models.TextField(blank=True, help_text='Parking area, Shared pool, Security features, Pets allowed, Furnished, Private gym, Elevator, Air conditioning, Partially furnished, Shared gym, Garden, Private pool, Sports court', max_length=1000, null=True, verbose_name='Mention features'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='PropertyTType_status',
            field=models.CharField(blank=True, choices=[('Apartment', 'Apartment'), ('Villa', 'Villa'), ('Duplex', 'Duplex'), ('RestHouses', 'RestHouses')], max_length=30, null=True, verbose_name='Property detail type'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='area',
            field=models.IntegerField(blank=True, help_text='Set area', null=True, verbose_name='area'),
        ),
    ]
