# Generated by Django 2.0.12 on 2020-03-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0004_auto_20200317_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='Description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='Title',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Title'),
        ),
    ]
