# Generated by Django 2.0.12 on 2020-03-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0005_auto_20200317_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='Location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Location'),
        ),
    ]
