# Generated by Django 2.0.12 on 2020-03-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0006_announcement_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='AnnouncementCoverImage',
            field=models.FileField(blank=True, help_text='Please upload a cover image for your announcement to make your property more attractive for customers.', null=True, upload_to='', verbose_name='Announcement cover image'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='ElseImage',
            field=models.FileField(blank=True, help_text='Please upload other medias for your announcement to make your property more attractive for customers', null=True, upload_to='', verbose_name='OtherImage'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='OtherDoc',
            field=models.FileField(blank=True, help_text='Floor plans, property license and any other information concerning to your property', null=True, upload_to='', verbose_name='Other documentations'),
        ),
    ]
